---
- name: Creating a new kubernetes secret
  hosts: kubernetes-master-node
  vars_files:
  - ../env_variables
  vars_prompt:

    - name: "add_namespace"
      prompt: "Do you want to create a new namespace (yes/no)?"
      private: no
      default: "no"

    - name: "new_namespace"
      prompt: "Enter new namespace name(Skip if you don't want to create one)"
      private: no
      when: add_namespace s== "yes"

    - name: username
      prompt: "What is your username?"
      private: no

    - name: password
      prompt: "What is your password?"
      unsafe: yes
      private: yes
      confirm: yes
    
    - name: namespace
      prompt: "Secret's namespace?"
      private: no



  tasks:



    

    - name: Creating the new namespace {{new_namespace}}
      shell: |
        source   /etc/environment 
        source  /home/{{user}}/.bash_profile 
        kubectl create ns {{new_namespace}}
      when: add_namespace == "yes"
      args:
        executable: /bin/bash
      retries: 3
      delay: 10
      register: result
      until: result.rc == 0



    - name: Creating a secret Logging into private registry 
      shell: |
        kubectl create secret  docker-registry regcred \
         --docker-server=registry.forge.orange-labs.fr \
         --docker-username="{{username}}" \
         --docker-password="{{password}}" \
         -n {{namespace}}
