---
- hosts: kubernetes-worker-nodes
  vars_files:
  - ../env_variables
  tasks:  
  - name: Copying token to worker nodes
    copy: src=/home/{{user}}/{{token_file}} dest=/home/{{user}}/join_token
  - name: Joining worker nodes with kubernetes master
    become: yes
    shell: |
     kubeadm reset -f
     cat /home/{{user}}/join_token | tail -2 > out.sh
     sh out.sh

