---
- hosts: all
  vars_files:
  - ../env_variables
  tasks:
  - name: Disabling Swap on all nodes
    shell: swapoff -a
    become: yes
    become_user: root
    args:
      executable: /bin/bash    
     
  - name: Commenting Swap entries in /etc/fstab
    become: yes
    become_user: root
    replace:
     path: /etc/fstab
     regexp: '(.*swap*)'
     replace: '#\1'
 
  - name: Enabling iptable bridge network
    become: yes
    shell: |
     modprobe br_netfilter
     sysctl net.bridge.bridge-nf-call-iptables=1
    ignore_errors: yes

  - name: Creating bridge network permanant config file
    become: yes
    file:
      path:  /etc/sysctl.d/k8s.conf
      state: touch
    ignore_errors: yes

  - name: Setting bridge network permanant config 
    become: yes
    blockinfile:
      path: /etc/sysctl.d/k8s.conf
      block: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1 
    ignore_errors: yes

  - name: Setting SELinux to permessive mode (CentOS)
    become: yes
    shell: |
      setenforce 0
      sed -i s/^SELINUX=.*$/SELINUX=permissive/ /etc/selinux/config
    when: ansible_os_family in ["CentOS","RedHat"]
    ignore_errors: yes



  

  
