---
- hosts: all
  vars_files:
    - ../env_variables 
  tasks:
    - name: OS Detecting test-CentOS
      shell: echo "Detected CentOS System"
      when: ansible_os_family in ["CentOS","RedHat"]

    - name: OS Detecting test-Ubuntu
      shell: echo "Detected Debian System"
      when: ansible_os_family == "Debian"

    - name: Changing hostnames
      become: yes
      shell:  hostnamectl set-hostname {{ansible_hostname}}

    - name: Add Hostname to /etc/hosts
      become: yes
      shell: grep -q 'k8s' /etc/hosts && echo exists || echo "{{ansible_host}} {{ansible_hostname}}" >> /etc/hosts
      register: result
      changed_when: result.stdout.find('exists') == -1

    - name: Installing Dependencies (Ubuntu)
      become: yes
      apt:
        name: [curl, wget, lvm2]
        state: latest
      when: ansible_os_family == "Debian"
      environment: "{{ proxy_env }}"

    - name: Installing Dependencies (CentOS)
      become: yes
      yum:
        name: [yum-utils, device-mapper-persistent-data, lvm2, wget]
        state: latest
      when: ansible_os_family in ["CentOS","RedHat"]
      environment: "{{ proxy_env }}"

    - name: Creating a repository file for Kubernetes (Ubuntu)
      become: yes
      file:
       path: /etc/apt/sources.list.d/kubernetes.list
       state: touch
      when: ansible_os_family == "Debian"

    - name: Adding Kubernetes repository gpg key (Ubuntu)
      become: yes
      shell: |
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      when: ansible_os_family == "Debian"
      environment: "{{ proxy_env }}"

    - name: Adding repository details in Kubernetes repo file  (Ubuntu)
      become: yes
      blockinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        block: |
          deb https://apt.kubernetes.io/ kubernetes-xenial main
      when: ansible_os_family == "Debian"

    - name: Creating a repository file for Kubernetes (CentOS)
      become: yes
      file:
        path: /etc/yum.repos.d/kubernetes.repo
        state: touch
      when: ansible_os_family in ["CentOS","RedHat"]

    - name: Adding repository details in Kubernetes repo file (CentOS)
      become: yes
      blockinfile:
        path: /etc/yum.repos.d/kubernetes.repo
        block: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      when: ansible_os_family in ["CentOS","RedHat"]

    - name: Installing Docker
      become: yes
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        chmod +x get-docker.sh
        ./get-docker.sh
      environment: "{{ proxy_env }}"

    - name: Installing Container SELinux (CentOS)
      become: yes
      yum:
        name: http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-1.el7_6.noarch.rpm
        state: present
      when: ansible_os_family in ["CentOS","RedHat"]
      environment: "{{ proxy_env }}"
      

    - name: Changing docker defaul cgroup.
      become: yes
      shell: |
        mkdir -p /etc/docker
        cat << EOF |  tee /etc/docker/daemon.json
        {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
        "max-size": "100m"
           },
        "storage-driver": "overlay2"
        }
        EOF

    - name: Adding Docker to $USER Group
      become: yes
      shell: |
        groupadd docker
        usermod -aG docker {{user}}
        systemctl daemon-reload
      ignore_errors: yes

    - name: Create Docker proxy service file
      become: yes
      shell: |
        mkdir -p /etc/systemd/system/docker.service.d

    - name: Copying docker proxy conf
      become: yes
      copy:
        src: "/home/{{user}}/docker-proxy.conf"
        path: "/etc/systemd/system/docker.service.d/http-proxy.conf"
        follow: yes
      when: docker_proxy.find("yes") != -1

    - name: Restarting Docker service
      become: yes
      shell: |
        systemctl daemon-reload
        systemctl restart docker

    - name: Installing Kubernetes (Ubuntu)
      become: yes
      apt:
        name: "{{ packages }}"
        state: present 
        update_cache: yes
      vars:
        packages:
        - kubectl={{ UBUNTU_K8S_VERSION }}
        - kubeadm={{ UBUNTU_K8S_VERSION }}
        - kubelet={{ UBUNTU_K8S_VERSION }}
      when: ansible_os_family == "Debian"
      environment: "{{ proxy_env }}"

    - name: Prevent kubeadm, kubectl, kubelet from upgrading
      become: yes
      shell:  apt-mark hold kubelet kubeadm kubectl
      when: ansible_os_family == "Debian"
      environment: "{{ proxy_env }}"

    - name: Installing Kubernetes (CentOS)
      become: yes
      yum:
        name: "{{ packages }}"
        state: present 
        update_cache: yes
      vars:
        packages:
        - kubectl-{{ CENTOS_K8S_VERSION }}
        - kubeadm-{{ CENTOS_K8S_VERSION }}
        - kubelet-{{ CENTOS_K8S_VERSION }}
      when: ansible_os_family in ["CentOS","RedHat"]
      environment: "{{ proxy_env }}"

    - name: Starting and Enabling docker service
      become: yes
      service:
        name: docker
        state: started
        enabled: yes

    - name: Starting and Enabling Kubelet service
      become: yes
      service:
        name: kubelet
        state: started
        enabled: yes
